version: '3.8'

volumes:
  wordpress:

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - '443:443'
    volumes:
      - wordpress:/var/www/html
    entrypoint: ["nginx", "-g", "daemon off;"]
  
  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    ports:
      - '9000:9000'
    volumes:
      - wordpress:/var/www/html
    entrypoint: ["tail", "-f"]
    #entrypoint: ["./usr/sbin/php-fpm7.3", "-F"]
