version: '3.9'

volumes:
  wordPress:
  DB:

networks:
  network:
    driver: bridge

services:
  nginx:
    env_file:
      - .env
    restart:
      on-failure
    volumes:
      - wordPress:/apphtml
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - 443:443
    networks:
      - network
    entrypoint: ["./nginx_config.sh"]

  mariadb:
    env_file:
      - .env
    restart:
      on-failure
    volumes:
      - DB:/var/lib/mysql
    build: ./requirements/mariadb/
    container_name: mariadb
    expose:
      - 3306
    networks:
      - network
    entrypoint: ["./DBSetup.sh"]

  wordpress:
    env_file:
      - .env
    restart:
      on-failure
    volumes:
      - wordPress:/apphtml
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    container_name: wordpress
    expose:
      - 9000
    networks:
      - network
    entrypoint: ["./wp_install.sh"]
