version: '3.8'
services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - '443:443'
    entrypoint: ["nginx", "-g", "daemon off;"]
  
  # wordpress:
  #   build: ./requirements/wordpress/
  #   ports:
  #     - 80:80
