version: '3.9'

volumes:
  wordpress:

networks:
  front:
  back:

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - '443:443'
    networks:
      - front
    volumes:
      - wordpress:/var/www/html
    entrypoint: ["nginx", "-g", "daemon off;"]
  
  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    expose:
      - 9000
    networks:
      - front
    volumes:
      - wordpress:/var/www/html
    entrypoint: ["/usr/sbin/php-fpm7.3", "-F", "-R"]
